language: php
matrix:
  fast_finish: true # Don't wait for the allowed failures to build.
  include:
  - php: 7.3
    env: PREFER_LOWEST=""
  - php: 7.2
    env: PREFER_LOWEST=""
  allow_failures:
    - php: 7.4
      env: PREFER_LOWEST=""

cache:
  directories:
  - vendor
  - $HOME/.composer

before_script:
- composer update

script:
- mkdir -p build/logs
- composer dump-autoload
- composer csfix # todo: use cscheck instead
- composer phpstan
- ./vendor/bin/phpunit

jobs:
  include:
    -
      stage: coverage
      php: 7.3
      name: Test Coverage
      script:
        - php vendor/bin/php-coveralls -v
